- package.json
- src/components/commons/SignInputController/index.tsx
- src/components/domains/signIn/SignInForm.module.scss
- src/components/domains/signIn/SignInForm.tsx
- src/constants/signInputCondition.ts
- src/layout/SignLayout/SignLayout.module.scss
- src/schemas/signInSchema.ts
- yarn.lock
- signin page에 버튼 컴포넌트를 추가 했습니다.
- signin page에 일부 스타일을 변경했습니다. 
- signin page의 폼을 관리할 때 zod를 이용하도록 리팩터링 했습니다.
-
-
-
> 예시) https://github.com/course-maker/Course-Maker-FE/issues/[이슈번호] > https://github.com/course-maker/Course-Maker-FEissues/2
close #2
> Feat: signin page에 버튼 컴포넌트 추가, 스타일 수정, zod를 이용해서 폼을 관리하도록 리팩터링

- src/api/axios.ts
- src/components/commons/SignInputController/index.tsx
- src/components/domains/signIn/SignInForm.tsx
- src/components/domains/signUp/Dropdown.tsx
- src/components/domains/signUp/EmailInput.tsx
- src/components/domains/signUp/EmailInputController.tsx
- src/components/domains/signUp/SignUpForm.tsx
- src/hooks/useAuth.tsx
- src/schemas/signUpSchema.ts
> Feat: axios interceptor 작성 및 sign page 버그 수정

- src/api/address.ts
- src/api/destination/index.ts
- src/api/destination/type.ts
- src/api/member/type.ts
- src/hooks/useDestinationMutation.ts
- src/layout/SpotRegisterLayout/index.tsx
- src/pages/PageRouter.tsx
- src/pages/spotEditPage/index.tsx
- 여행지 edit 페이지 구현
-
-
-
-
-
close #[이슈번호]
> Feat: 여행지 edit 페이지 구현

- src/components/commons/Modal/index.tsx
- src/components/commons/QuillEditor/index.tsx
- src/components/domains/signIn/AlertModal.tsx
- src/components/domains/signIn/SignInForm.tsx
- src/components/domains/spotRegister/DestinationDetailsInput.module.scss
- src/components/domains/spotRegister/DestinationDetailsInput.tsx
- src/components/domains/spotRegister/MainImageInput.tsx
- src/hooks/useImageUpload.ts
- src/hooks/useSignInMutation.ts
- src/layout/SpotRegisterLayout/index.tsx
- src/utils/CustomImageBlot.ts
- 여행지 등록하기 페이지에서 대표 이미지 url api 요청 시점을 submit 시점으로 제한 했습니다.
- react quill에 변경한 이미지 사이즈가 반영 안되는 버그를 고쳤습니다.
- 여행지 등록하기 페이지의 대표 이미지 인풋 영역에 helper text를 추가했습니다.
- 여행지 등록하기 페이지에서 글 작성 중 새로고침을 눌렀을 때 경고 메세지가 뜨도록 했습니다.
- 모달에서 키보드 이벤트가 작동하도록 했습니다.
- 로그인 에러 상태 코드가 변경되어 이를 반영했습니다.
-
-
-
close #[이슈번호]
> Fix: 마이너한 버그들 수정 및 UI 변경 사항 반영

- .gitignore
- src/components/commons/BadgeList/BadgeList.tsx
- src/components/commons/Banner/Banner.tsx
- src/components/commons/Card/Card.tsx
- src/components/commons/ItemBox/ItemBox.tsx
- src/pages/CourseDetailPage/index.tsx
- src/pages/CourseRegisterPage/index.tsx
- src/pages/HomePage/data.ts
- src/pages/HomePage/index.tsx
- src/pages/SearchPage/index.tsx
> Feat: build 에러 해결

- src/components/commons/Steppers/Steps/Step2/Step2.module.scss
- src/components/commons/Steppers/Steps/Step2/Step2.tsx
- src/components/commons/Steppers/Steps/Step3/Step3.module.scss
- src/pages/CourseDetailPage/CourseDetailPage.module.scss
- src/pages/CourseDetailPage/index.tsx
- src/pages/SpotDetailPage/index.tsx
- 코스 상세페이지 content 부분 p 태그 생기는 현상 제거
- Day 버튼 Active 상태일 때 색상 변경
- Step2 Minus Button 추가했습니다.
-
-
-
> https://github.com/course-maker/Course-Maker-FE/issues/59
close #59
> Feature design refactor

- src/pages/CourseDetailPage/CourseDetailPage.module.scss
- src/pages/CourseDetailPage/index.tsx
- 코스 상세페이지 UI/UX 작업 수정했습니다.
-
-
-
-
-
> https://github.com/course-maker/Course-Maker-FE/issues/61
close #61
> Fix-코스 상세 페이지 수정

- src/components/commons/Steppers/Steps/Step1/Step1.module.scss
- src/components/commons/Steppers/Steps/Step2/Step2.module.scss
- src/components/commons/TitleBox/TitleBox.module.scss
- src/components/domains/courseRegister/BadgeListTemp/BadgeListTemp.module.scss
- src/components/domains/courseRegister/BadgeListTemp/BadgeListTemp.tsx
- src/components/domains/courseRegister/BadgeLists.tsx
- src/pages/SpotDetailPage/index.tsx
-
-
-
-
-
-
> https://github.com/course-maker/Course-Maker-FE/issues/64
close #64
> Feature refactor UI

- src/components/commons/Steppers/Steps/Step1/Step1.tsx
- src/components/commons/Steppers/Steps/Step2/Step2.tsx
- src/components/commons/Steppers/Steps/Step3/Step3.module.scss
- src/components/domains/courseRegister/BadgeListsController.tsx
-
-
-
-
-
-
> https://github.com/course-maker/Course-Maker-FE/issues/66
close #66
> Fix: 코스 등록하기 ui 수정

- src/pages/CourseDetailPage/CourseDetailPage.module.scss
- src/pages/SpotDetailPage/SpotDetailPage.module.scss
> Fix: 여행지, 코스 디테일 페이지 스타일 수정

- package.json
- src/assets/styles/base/_reset.scss
- src/components/commons/Button/Button.module.scss
- src/components/commons/Button/index.tsx
- src/components/commons/Modal/ModalContentBox.module.scss
- src/components/commons/Modal/ModalContentBox.tsx
- src/components/commons/Modal/index.tsx
- src/layout/SignLayout/SignLayout.module.scss
- src/layout/SignLayout/index.tsx
- 모바일 기기에서 버튼에 접근 시 호버 이벤트 발생 방지
- 로그인 페이지 반응형 구현
- 모달 반응형 구현
- 
-
-
-
close #84
> Design: 버튼, 로그인페이지, 모달에 반응형 구현

- src/api/address.ts
- src/api/member/index.ts
- src/api/member/type.ts
- src/components/commons/NavigationBar/RightButtons.tsx
- src/constants/modals.ts
- src/hooks/useLogoutMutation.ts
- src/hooks/useSignInMutation.ts
- src/utils/manageTokenInfo.ts
- 로그인 및 로그아웃 관련 변경된 API로 수정
- 로그인 오류, 로그아웃 성공 시 모달 기능 추가
-
-
-
-
close #86
> Fix: 로그인 및 로그아웃 관련 변경된 API  반영 및 모달 기능 추가

- src/components/domains/detail/Review/ReviewForm.tsx
- src/components/domains/detail/Review/index.tsx
- src/type/type.d.ts
> Fix: 리뷰 수정 시 포커스가 옮겨 가도록 수정

- package.json
- src/api/course/index.ts
- src/api/course/register.ts
- src/api/course/type.ts
- src/components/domains/courseRegister/OptionController.tsx
- src/components/domains/courseRegister/SliderBar.module.scss
- src/components/domains/courseRegister/SliderBar.tsx
- src/constants/courseInputs.ts
- src/constants/initialValues.ts
- src/hooks/course/mutations/test.ts
- src/hooks/course/mutations/useCourseMutation.ts
- src/layout/CourseRegisterLayout/CourseRegisterLayout.module.scss
- src/layout/CourseRegisterLayout/index.tsx
- src/pages/CourseRegisterPage/index.tsx
- src/utils/validateCourseFormData.ts
- yarn.lock
- 코스 등록 페이지 작업중
- 현재 경로 설정 부분 구현 필요
- 코스 등록을 하면 여행 인원을 추가하라는 에러가 남. 확인 필요
- #109 
close #[이슈번호]
> Feat: 코스 등록 UI 및 기능 50%

- src/components/commons/CardList/AllCardList.tsx
- src/components/commons/Modal/Modal.module.scss
- src/components/commons/SliderBar/SliderBar.tsx
- src/components/commons/Steppers/Steps/Step1/Step1.tsx
- src/components/domains/courseRegister/DestinationList.tsx
- src/components/domains/courseRegister/DestinationsInputController.tsx
- src/components/domains/courseRegister/SliderBar.module.scss
- src/components/domains/courseRegister/SliderBar.tsx
- src/components/domains/courseRegister/TravelCourseOnMap.module.scss
- src/components/domains/courseRegister/TravelCourseOnMap.tsx
- src/components/domains/destinationRegister/DestinationsInputController.tsx
- src/components/domains/detail/course/CourseInfo/TravelCourseOnMap/TravelCourseOnMap.module.scss
- src/components/domains/detail/course/CourseInfo/TravelCourseOnMap/index.tsx
- src/constants/courseInputs.ts
- src/hooks/destination/queries/useGetDestinationQuery.ts
- src/layout/CourseRegisterLayout/index.tsx
- src/pages/CourseRegisterPage/index.tsx
- src/utils/validateCourseFormData.ts
- 경로 설정 모달창 및 기능 구현
- #109 
close #[이슈번호]
> 경로 설정 모달창 및 기능 구현

- src/components/domains/courseRegister/SliderBar.module.scss
- src/pages/CourseRegisterPage/index.tsx
- 코스 등록 등급별 접근 권한 막기
-
-
-
close #[이슈번호]
> Feat: "코스 등록 등급별 접근 권한 막기"

- src/components/domains/detail/course/CourseInfo/TravelCourseOnMap/DestinationList.tsx
- src/components/domains/detail/course/CourseInfo/TravelCourseOnMap/TravelMap.tsx
- src/components/domains/detail/destination/DestinationMain/DestinationMain.tsx
> 여행지 좌표가 없을 시 주소로 위치 찾는 기능 구현

- src/components/domains/detail/course/CourseInfo/TravelCourseOnMap/index.tsx
- src/layout/SignLayout/index.tsx
- src/pages/SignInPage/index.tsx
> oauth UI 삭제 및 길찾기 오류 해결

- src/components/commons/SignInput/SignInput.module.scss
- src/components/commons/SignInput/index.tsx
- src/components/commons/SignInputController/index.tsx
- src/components/domains/myPage/contents/UpdateUserInfo/UpdateUserInfo.module.scss
- src/components/domains/myPage/contents/UpdateUserInfo/index.tsx
- 마이페이지 회원정보 수정 폼 UI 작업
- 이메일
- 비밀번호 변경
- 이름
- 닉네임
- 휴대폰 번호
-
- #156 
close #[이슈번호]
> 마이페이지 회원정보 수정 폼 UI 작업

- src/api/address.ts
- src/api/member/index.ts
- src/api/member/type.ts
- src/components/domains/myPage/contents/Delete/Delete.module.scss
- src/components/domains/myPage/contents/Delete/index.tsx
- src/constants/modals.ts
- src/hooks/useWithDrawalMutation.ts
- 회원 탈퇴 UI 및 api 연동
-
-
-
- #162 
close #[이슈번호]
> Feat: "회원 탈퇴 UI 및 api 연동"
